language: scala
scala:
   - 2.12.2
jdk:
  - openjdk8

install:
  - . $HOME/.nvm/nvm.sh
  - nvm install 7
  - nvm use 7
  - export NODE_PATH="$(npm config get prefix)"/lib/node_modules
  - npm install
  - npm install jsdom source-map-support
  - npm install -g jshint

script:
  - sbt ++$TRAVIS_SCALA_VERSION test
  - jshint app/jvm/src/main/resources/
  - jshint app/jvm/src/main/assets/

# Taken from https://github.com/typelevel/cats/blob/master/.travis.yml
before_cache:
  - find $HOME/.sbt -name "*.lock" -type f -delete
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -type f -delete
cache:
  directories:
    - $HOME/.sbt/0.13/dependency
    - $HOME/.sbt/boot/scala*
    - $HOME/.sbt/launchers
    - $HOME/.ivy2/cache
    - "node_modules"
